let math_env = {
	"exp": Math.exp,
	"pow": Math.pow,
	"log": Math.log,
	"sin": Math.sin,
	"cos": Math.cos,
	"tan": Math.tan,
	"sinh": Math.sinh,
	"cosh": Math.cosh,
	"tanh": Math.tanh,
	"asin": Math.asin,
	"acos": Math.acos,
	"atan": Math.atan,
	"Math_atan2": Math.atan2,
};
